### ISSUE TITLE
Avoid broken links on docs.typo3.org

### ISSUE THREAD

**Issue by tmotyl** [TYPO3-Documentation/T3DocTeam#37] opened 2018-09-22 19:32 UTC
A SEO crawler found
- 841 resources with 4xx status code
- 2 resources with 5xx status code
- 5545 broken links

crawler was honoring the robots.txt, so singlehtml pages were not included

I attach a zip with csv files containing list of broken links and urls of pages containing them.

[broken_links_report_22_09_2018.zip](https://github.com/TYPO3-Documentation/T3DocTeam/files/2408094/broken_links_report_22_09_2018.zip)

**Comment by marble** [comment] 2018-09-23 17:23
So, what can we learn from this? From a first inspection:

Sometimes there is a simple reason for _many_ wrong links. Example: The urls for _issues_ and _repository_ are just defined wrong. So each page will show up with several wrong links "by definition":
![image](https://user-images.githubusercontent.com/307057/45930874-ba1f0f80-bf65-11e8-8243-9c3741329ad8.png)
The same is wrong for "7-6". 
All of those bad links are in docs marked as "outdated" (archive) and "related link" area.

**Comment by marble** [comment] 2018-09-23 17:31
Note to myself: The rendering toolchain should include a linkchecker.

**Comment by marble** [comment] 2018-09-23 17:33
Another systematic error that is the cause for many wrong links: The singlehtml-Version should not have the list of reference targets.

**Comment by tmotyl** [comment] 2018-09-23 18:45
Thanks for the investigation @marble, I suspect that the pareto rule 80/20 is also valid here and many broken links can be fixed with few fixes.
Let me know if you need an updated report.

**Comment by sypets** [comment] 2018-10-09 15:20
There is another issue for broken links: #5. 

To sort this out further. We can differentiate between:

1. broken backlinks: links on other sites that point to this site (e.g. blogs, search engines etc.). Cause of problem, usually renaming of manual, pages, restructuring etc.
2. broken links on docs.typo3.org. Several reasons, some of them mentioned above. 

The other issue #5 adresses 1 (broken backlinks to docs.typo3.org). This issue adresses 2 (broken links on docs.typo3.org). When the above problems are fixed, the other problems can be solved by e.g. redirects, etc.

**Comment by marble** [comment] 2018-10-18 15:05
https://typo3.slack.com/archives/C028JEPJL/p1539854472000100

Oliver Hader [11:21 AM]
Hi folks, since the security guide has been moved around links like e.g. https://docs.typo3.org/typo3cms/SecurityGuide/HackedSite/FurtherActions/Index.html end up in a 404.
I’d like to ask for additional redirects to the new location since these links have been used a lot in security advisories and are currently still indexed on google. Thanks in advance!


Martin Bless [4:33 PM]
@olly Yes, indeed. Thanks for reporting. Let me see how we can do this.

**Comment by tmotyl** [comment] 2018-10-19 10:03
I've added redirects for the security guide
please let me know if you find sth missing

**Comment by marble** [comment] 2018-11-12 08:31
Bastian reports this 404: https://docs.typo3.org/typo3cms/extensions/core/8.7/Changelog/7.5/Important-67954-MigrateCTypesTextImageAndTextpicToTextmedia.html

**Comment by sypets** [comment] 2018-11-12 10:07
Really weird URL. Should be https://docs.typo3.org/typo3cms/extensions/core/latest/Changelog/7.5/Important-67954-MigrateCTypesTextImageAndTextpicToTextmedia.html

I think we used to have other branches on there and now there is only latest? Is that correct?

Can we come up with some common rules that will safely redirect, such as

`(typo3cms\/extensions\/core\/)([^\/]*(?!latest))(\/Changelog\/.*)`  >> $1latest$2

**Comment by marble** [comment] 2018-11-15 19:39
https://typo3.slack.com/archives/C028JEPJL/p1542279627227600
Christian Kuhn [12:00 PM]
the new redirect from `https://docs.typo3.org/typo3cms/SecurityGuide/` to `https://docs.typo3.org/typo3cms/CoreApiReference/Security/` kills the link to the old sec guide on `https://docs.typo3.org/typo3cms/References/Index.html`  -  the compiler tries to fetch `https://docs.typo3.org/typo3cms/SecurityGuide/objects.inv` which is redirected and then does not exist ... i'd suggest to at least blacklist objects.inv from the redirect so cross linking to old docs still works. if we don't fix this, i'll have to hard code the old link which isn't nice, either.    could anyone step in to help / fix this?

note the purpose of this link is to be able to see "old" version of the documents that have been integrated into core api. so the "rewrite everything" approach kill that too. maybe the generic rewrite should be removed again for now. it does more bad than good at the moment?

**Comment by tmotyl** [comment] 2018-11-17 22:02
Hi
Sorry i dont have time right now to fix it. 
probably the way to go is to provide redirects for every page separately instead of generic redirect?

**Comment by marble** [comment] 2018-11-18 12:12
@tmotyl Maybe - I understand the desire of many people to get this right. But, as we see, that consumes a lot of effort. Thanks for letting us know you don't have the time right now. Keep up the good work!

**Comment by sypets** [comment] 2018-11-18 13:00
... hmm ... even if this not solvable right away, it is a real annoyance and I would vote to keep this issue open. 

We _regularly_ get reports of broken links via Slack or as issues. Often, it opens a discussion, often it does not get resolved. Even if this is closed now, new issues will be opened and broken links reported in the channel.

What I don't understand, why we can't create a few redirects if things are restructured. Why is that such a big problem and why do people think it is unnecessary when it is a pretty big annoyance to several people again and again, and broken links are reported again and again, like recently by Oliver Hader.

The t3o relaunch started with a lot of broken links as well, but most (or at least a lot) of these got resolved (AFAIK), also see https://git-t3o.typo3.org/t3o/typo3.org/issues/281

I have not given up on this topic. But no access to server, which is kind of a handicap for this task and also pretty annoying if you are willing to do the work, just got started and then get kicked out.

**Comment by sypets** [comment] 2018-11-30 14:29
Please see https://github.com/TYPO3-Documentation/redirects

Some redirects have been added. These can be used with RewriteMap or to create redirects in .htaccess.

**Comment by stucki** [comment] 2019-02-12 13:56
@sypets Since you just closed https://github.com/TYPO3-Documentation/T3DocTeam/issues/55 I'd like to remind you that I posted a pretty simple solution for this problem. So far no feedback from anyone, but I'd say this just needs to be applied... :-)

**Comment by sypets** [comment] 2019-02-12 14:23
https://github.com/TYPO3-Documentation/T3DocTeam/issues/55#issuecomment-448384726

@stucki @marble we are at the current t3o sprint with Daniel. There are several .htaccess files on doc server, and we had difficulties applying simple RewriteRule in existing .htaccess because of sideeffects. We decided to not proceed. Who has maintained this in the past? Would probably be the best idea, that this person proceeds with this task.

Closing 2 of 3 existing issues was just my attempt to reduce noise on this issue.

**Comment by stucki** [comment] 2019-02-12 14:38
Wasn't me, but I offered my help. However, didn't get any feedback since then...

**Comment by DanielSiepmann** [comment] 2019-03-01 15:33
There are many different issues open regarding this single topic.

Let's try to focus all efforts in a single issue.

As @sypets wrote we tried to setup redirects during our Sprint in Wiesbaden and gave up due to the current situation. This is not to blame anyone, but we were just not able to invest enough time into this topic, beside further topics we tried to finish during this sprint.

The current situation is as following (already described by @marble within https://github.com/TYPO3-Documentation/T3DocTeam/issues/42):

Right now, there is a single `.htaccess` file which is symlinked into each folder providing a single manual.
The folder structure looks like this:

```
.
├── docroot
│   └── typo3cms
│       └── ExtbaseGuide
│           ├── 6.2
│           ├── latest
│           └── stable -> latest
└── someotherfolder
    └── _htaccess-2016-08.txt
```

The file content:
```
Options +Indexes

RewriteEngine On

# Do not rewrite URLs starting with any valid version number followed by a slash
RewriteRule ^[0-9]+(\.[0-9]+)(\.[0-9]+)*(-dev)?/(.*)$ -  [L]

# Do not rewrite URLs like '8-dev/'
RewriteRule ^[0-9]+-dev/(.*)$ -  [L]

# Do not rewrite URLs starting with the provided words
RewriteRule ^(latest|master|packages|stable)(.*)$ -  [L]

# still needed?
RewriteRule ^manuals.json(.*)$ -  [L]

# Rewrite other cases into the folder stable/
RewriteRule ^(.*)$ stable/$1
```

This already prevents us from redirecting many of the current situations we encounter. Three rules are in place which prevent further redirects. Apache will lookup `.htaccess` from the lowest to top folder, finding this symlinked file first. This file already prevents further redirects in most cases.

`.htaccess` files are also not able to include further files, so we could not include more specific files for each manual.

We could adjust this globally used file to contain further redirect rules, prefixed for each manual. I guess? Also http://httpd.apache.org/docs/current/mod/mod_rewrite.html#rewriteoptions is available, which might be another way to solve this, but I would guess it will be no help, as we do not have a level in between.

I'm not an server admin and just able to configure some basics within Apache. But I'll try to force this topic for now and get in contact with people from the community who are able to get rid of this issue.

**Comment by DanielSiepmann** [comment] 2019-03-02 22:24
Solved together with https://github.com/TYPO3-Documentation/T3DocTeam/issues/3.

We now have a `404.php` which will check a mapping of old url => new url. This works for now and can be improved in the future, if necessary.

**Comment by DanielSiepmann** [comment] 2019-03-02 22:24
I keep this issue open, as we have to add the mapping.

**Comment by linawolf** [comment] 2023-10-20 18:10
It seems like this is solved

**Closed as completed by linawolf** 2023-10-20 18:10 UTC
Labels: bug
